Latex/vorlage.tex
=> hyperref Paket hinzugefügt (inkl. Lesezeichen für PDF usw)

.gitignore
wenn SVGs included werden wird dieser Ordner für temporäre Dateien erstellt
=> in GitIgnore svg-inkscape ausgeschlossen

Latex/vorlage.tex
Dieses Paket verbessert deutlich die Typografie, siehe https://www.teuderun.de/latex/layout/microtype-paket/
Reduziert extrem über-/untervolle Boxen
=> Paket microtype eingebunden

.gitignore, Latex/inhalt_example/Erklärung.tex, Latex/inhalt_example/LIES MICH.txt, Latex/inhalt_example/Titelseite_3Autoren.tex, Latex/inhalt_example/Titelseite_Praxisbeleg.tex, Latex/vorlage.tex, README.md
neues System für globale Metadaten - inkompatibel zu alten Dokumenten, PDF Lesezeichen jetzt mit Kapitelnumemr
=> neues Metadaten-System

Latex/inhalt_example/metadaten.sty, Latex/vorlage.tex
Formatierung der Schriftart bei Titel und URL angepasst, Abgrenzungen zwischen Namen und Titel angepasst, Abrufdatum angepasst, Punkte am Ende entfernt
=> Quellenverzeichnis Formatierung angepasst

Latex/inhalt_example/Anhang.tex, Latex/vorlage.tex
yay
bin mir nicht sicher ob du das auf master oder dev mergen wolltest, kann ich sonst auch nochmal rebasen falls das nicht direkt auf dev gehen würde.
closes #25
=> Umlaute in PDF-Meta

Latex/vorlage.tex
=> Captions linksbündig, selbst wenn nur einzeilig

HINWEISE.md, README.md
* Vereinfachung der README
* 
* Auslagerung in Hinweise.md
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/63"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Dev readme changes (#62)

.github/workflows/document-build.yml, .gitpod.yml, .vscode/settings.json
weniger nerviges pythontex
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/72"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> bump build container v1.1.0 -> v1.1.1 und container version in GH actions/gitpod

.github/workflows/document-build.yml, .vscode/settings.json
ist ne hilfs-PR um änderungen an GHA zu tracken.
note to self: am besten squashen wegen dreckigen commits :D
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/79"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> diff-pdf für GH actions

.github/workflows/document-build.yml
closes #82
testläufe unter https://github.com/jemand771/Vorlage-Latex/actions
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/83"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix für kaputte diff-action auf neuem branch

README.md
Text etwas seriöser gestaltet, Gitpod Link eingefügt, andere Links ergänzt
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/90"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> README.md angepasst

Latex/inhalt/Abkürzungen.tex, Latex/inhalt/Anhang.tex, Latex/inhalt/Kapitel1.tex
- Abkürzungen korrekt sortiert
- Anhang 1 seriös gestaltet
- Anhang zwei ✨verbessert✨ (seriös af, aber da musste ein YT-Video hin. Alternative: den Punkt streichen)
- Kapitel1.tex: 
- Grammatik korrigiert, seriöser gestaltet
- Links als Beispiele ergänzt
- SVG-Beispiel ergänzt.
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/92"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Dev hotfix des hotfix weil @DSczyrba ungeduldig ist

Latex/vorlage.tex
Fixes #93 
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/96"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Abstände bei Umgebungen gefixt

Latex/inhalt/Erklärung_3Autoren.tex, Latex/inhalt/Erklärung_Praxisbeleg.tex
kwt
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/102"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Erklärung zu den Latex-Dokumenten entfernt

Latex/inhalt/Abstract_Freigabeerklärung_Bachelorthesis.tex, Latex/inhalt/Anhang.tex, Latex/inhalt/Erklärung_3Autoren.tex, Latex/inhalt/Erklärung_Praxisbeleg.tex, Latex/metadaten.sty
- Abstract zur Bachelorthesis und Freigabeerklärung nach BA-Vorbild integriert aber noch deaktiviert
- etwas Formatierung
- Warnungen reduziert
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/106"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Abstract und Freigabeerklärung

.vscode/settings.json, Latex/inhalt/Abstract_Freigabeerklärung_Bachelorthesis.tex, Latex/inhalt/Anhang.tex, Latex/inhalt/Erklärung_3Autoren.tex, Latex/inhalt/Erklärung_Praxisbeleg.tex, Latex/inhalt/Kapitel1.tex, Latex/light/vorlage_light.tex, Latex/main.tex, Latex/vorlage.tex
Vorher: 
Nachher:
Außerdem Container Version 1.5.1->1.6.1
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/121"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Minted Style verbessert / Container Version Bump / Dateiendungen entfernt

Latex/literatur.bib, Latex/vorlage.tex
Nachnamen bzw. Origanisationsnamen werden hiermit automatisch in all CAPS geschrieben.
=> Nachnamen automatisch in CAPS, maximal 3

Latex/literatur.bib, Latex/vorlage/Doku-Test.tex, Latex/vorlage/vorlage.tex
Zielversion: 2.1.3
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/147"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Korrektur bei mehr als drei Autoren

Latex/light/vorlage_light.tex, Latex/vorlage/vorlage.tex
wollen wir das? Ich denke schon
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/157"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Anhangsverzeichnis

.gitpod.yml, .vscode/extensions.json, .vscode/settings.json
Immer wenn eine der Latex-Dateien gespeichert wird, wird automatisch der "Build + Refresh" Task ausgeführt
=> Trigger hinzugefügt um Build-Task beim Speichern auszuführen

Latex/main.tex, Latex/metadaten.sty, Latex/vorlage/Sperrvermerk.tex
Sperrvermerk mit Toggle in der Metadaten.sty
Probleme: eine overfull vbox, die ich mir nicht erklären kann, kein Titel in der Kopfzeile rechts.
Hab beide nicht behoben bekommen... @DSczyrba  ?
=> Sperrvermerk hinzugefügt

.vscode/tasks.json
=> abstract task auch für windows anpassen

.gitpod.yml
Unötige Dinge wurden entfernt :D
=> Dev gitpod anpassungen

HINWEISE.md, Latex/vorlage/Doku-Test.tex, Latex/vorlage/vorlage.tex
=> Formel-Beispiel eingebaut und Formel-Caption korrekt formatiert

Latex/inhalt/Abkürzungen.tex, Latex/inhalt/Anhang.tex, Latex/light/main.tex, Latex/main.tex, Latex/vorlage/Doku-Test.tex, Latex/vorlage/Erklärung_1Autor.tex, Latex/vorlage/Erklärung_common.tex, Latex/vorlage/Freigabeerklärung_Bachelorthesis.tex, Latex/vorlage/Platzhalter_Themenblatt.tex, Latex/vorlage/Sperrvermerk.tex, Latex/vorlage/vorlage.tex, Latex/vorlage/vorlage_commands.tex
Der Name is eindeutig WIP 😅 
Umbau auf andere Klasse - scrreprt, unterstützt eine weitere Gliederungsebene: chapter
Alle Überschriften "rutschen" um eine Ebene - breaking Change - neue Majorversion 4.0
=> 4.0 - Klassenkampf

Latex/literatur.bib
- URL angepasst
- Datum angepasst
- Version hinzugefügt
- Autorenreihenfolge alphabetisch
=> Quelle Vorlage angepasst

Latex/inhalt/Anhang.tex, Latex/vorlage/bilder/usb.svg, Latex/vorlage/vorlage_subs/custom_commands.tex
=> CD Anhang überarbeitet

.github/workflows/document-build.yml
Abstract und Zustimmung zusätzlich zu main.pdf bauen
=> GH Actions für Abstract & Zustimmung

Latex/vorlage/Sperrvermerk.tex
fixes #220 
Passt die Formulierung des Sperrvermerks je nach Metadaten an
=> Sperrvermerk automatisch anpassen
