ba-latex/Vorlage-Latex

- .gitignore
Git beschwert sich sonst (wahrscheinlich wegen des Zeitstempels), dass der Ordner geändert wurde.
> in GitIgnore inhalt komplett ausgeschlossen

- Latex/inhalt_example/Titelseite_Praxisbeleg.tex
- Latex/inhalt_example/metadaten.sty
- Latex/vorlage.tex
Felder für Adresse von Autor und Praxispartner in Titelseite eingefügt, Hinweis in metadaten.sty eingefügt, veraltete Befehle \clearscrheadings und \clearscrplain durch aktuelle Äquivalente ersetzt, Paket lineno (wurde vorher scheinbar eh implizit geladen) explizit vor csquotes laden um Warnung zu verhindern
> Titelseite Praxisbeleg angepasst, Zukunftssicherheit verbessert

- Latex/inhalt_example/Erklärung_3Autoren.tex
- Latex/inhalt_example/Erklärung_Praxisbeleg.tex
- Latex/inhalt_example/Titelseite_Praxisbeleg.tex
- Latex/vorlage.tex
- README.md
Titelseiten und Erklärungen sollten bei langen Überschriften keine Probleme mehr machen, README aktualisiert und Datum korrigiert
> Titelseiten, Erklärungen, README gefixt

- Latex/inhalt_example/Anhang.tex
- Latex/inhalt_example/Titelseite_Praxisbeleg.tex
Abstand zwischen "Vorgelegt am" und "Von" auf 1-Autor Titelseite wiederhergestellt, \newpage in Anhang.tex durch \clearpage ersetzt, fixes #46 (zumindest laut @jemand771
> Abstand Titelseite + #46 fix

- .github/workflows/document-build.yml
hat bisschen gedauert, aber hier ist es! Bei jedem push oder PR wird eine pdf gebaut und archiviert. In diesem repo hilft uns das, syntaktische Fehler in Vorlage und Beispieldateien zu finden.
Der eigentliche Sinn der sache: In forks bzw. Beleg-Repos mit diesem hier als upstream existiert dann immer eine main.pdf auf dem gleichen Stand wie der aktuelle Code. Das soll Konsistenz schaffen, ersetzt aber _nicht_ die lokalen Builds via docker/LaTeX workshop/TeXMaker/...
related: #47, da fehlt allerdings noch wiki-zeugs
> PDF-Builds per GitHub actions

- .gitpod.yml
- .vscode/extensions.json
Helfen bei der einrichtung ausserhalb von gitpod, wo extensions nicht automatisch instaliert werden können
wenn ihr noch mehr extensions-wünsche habt wäre hier die gelegenheit die mit reinzumogeln ^^
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/64"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> VSCode-extensions aus .gitpod.yml empfehlen

- .gitpod.yml
- .vscode/settings.json
- .vscode/tasks.json
Das bringt eher für die Zukuft was, als für jetzt: wenn man nach viele Änderungen an Vorlage+Container wieder zurück zu einem alten Stand will, gibt es bisher keine möglichkeit, einen alten container zu bekommen (ausser das image selbst zu bauen)
Ab dieser PR wird der build-container über seine version festgelegt, statt einfach immer den neuesten zu verwenden
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/67"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Build-Container versionieren

- .vscode/settings.json
neu in dieser version: pythontex support
brauchen wir gerade noch nicht, das benutz' ich aber für die dynamischen metadaten -> früher oder später muss das sowieso rein ^^
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/68"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> bump buildcontainer v1.0.0 -> v1.1.0

- .gitignore
- .vscode/settings.json
- .vscode/tasks.json
siehe rocketchat und #59 und https://github.com/jemand771/latex-build/issues/5 für mehr infos
kurzversion: synctex geht bis auf forward unter windows, und das wird in der nächsten latex workshop version gefixed
nicht mergen, das docker-image steht noch auf `experimental` bis ich da ne neue version raus hab ^^
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/73"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> synctex support

- .vscode/settings.json
fix für \inputminted+autogobble
closes #70 
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/74"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> bump container -> v1.2.1

- .gitpod.yml
der task-typ prebuild wird deprecated, stattdessen soll init benutzt werden. weil init auch beim workspace-start ausgeführt wird, fällt der command task gleich mit weg. hätte man eigentlich auch eher drauf kommen können
die PR ist identisch zu #75 aber ich wollte den workspace prebuild nochmal triggern :D
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/76"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> gitpod: prebuild -> init (2)

- .vscode/tasks.json
die Windows Befehle werden auf powershell ausgeführt, diese nutzt del nur als alias zu "Remove-Item"
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/77"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Hotfix Windows Clean

- .github/workflows/document-build.yml
- .gitignore
- .vscode/settings.json
- .vscode/tasks.json
* support für diff-pdf
* diff-pdf ist aus performancegründen standardmässig deaktiviert
hinweis: das `--init` braucht man für diff-pdf, und weil man das leicht vergisst hab ich's mal als default mit rein genommen. das ändert potenziell das handling von signalen (SIGTERM etc.) an den prozess, was uns aber egal sein kann (abgebrochene builds nützen einem sowieso nichts)
@TheColin21 teste mal unter windows wenn du kannst ^^
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/78"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> bump buildcontainer -> v1.5.0 und diff-pdf

- .vscode/tasks.json
json kommentare: `#` ersetzen durch `//`
bin überrascht dass das überhaupt ging, aber naja
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/81"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> mini-fix weil colin doof ist

- Latex/vorlage.tex
häufig genutzte Pakete "listings" und "tikz" hinzugefügt
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/85"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Pakete hinzugefügt

- .vscode/settings.json
verboserer diff-pdf output im container (analog zu gha)
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/87"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> bump buildcontainer -> v1.5.1

- .vscode/keybindings.json
- .vscode/settings.json
- HINWEISE.md
Beinhaltet bereits STRG+ALT+J was zum Zeitpunkt dieses commits noch nicht funktioniert. Sollte in nächstem Commit gefixt werden.
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/86"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Synctex Fix und in Hinweise aufgenommen

- .gitpod.yml
note: das ist kein sicherheitsrisiko-weil der port standardmässig auf private steht. der port ist erst von aussen benutzbar, wenn man ihn in gitpod manuell auf public schaltet
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/94"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> nginx für externe pdf previews in gitpod

- .gitpod.yml
temporärer workaround für das enter-problem auf 8.20.2
note: synctex geht dadurch nicht kaputt, weil nur auf windows >=8.20.x gebraucht wird.
je nachdem, wie lange sich https://github.com/James-Yu/LaTeX-Workshop/issues/2845 zieht reverten wir das sicher bald wieder
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/95"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> gitpod latex-workshop downgrade

- Latex/vorlage.tex
Ja, was soll man sagen, ist halt nicht mehr :D
Das einzeilige macht keine Probleme.
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/100"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fixed Spacing inputminted

- .vscode/extensions.json
- .vscode/settings.json
Wir haben vorher die Erweiterungen "Bracket Pair Colorizer" empfohlen.
Diese wurde seit ca. 3 Jahren nicht aktualisiert und hat nicht mehr fehlerfrei funktioniert. Es gab zwar eine zweite Version, aber auch die ist unmaintained.
VS Code bietet seit Version 1.60 selbst diese [Funktion](https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization)
Und das beste: das ganze funktioniert korrekt.
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/116"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Veraltete Extension durch VS Code natives Setting ersetzt

- .gitpod.yml
Die aktuelle Version 1.10 funktioniert in Gitpod (zumindest mit VS Code latest, ohne hab ich nicht getestet, aber @jemand771 findet sicher raus, was die aktuelle mindestversion ist)
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/117"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Neuere Statusbar Commands Versionen freigeben

- .gitpod.yml
neuste version wieder freigeben, statt auf 8.19.2 zu hardcoden - das problem wurde upstream behoben und die kaputte version wird durch den nächsten release verdrängt
closes #112
erst mergen, wenn https://github.com/James-Yu/LaTeX-Workshop/releases bzw. https://open-vsx.org/extension/James-Yu/latex-workshop ein neues release hat ODER https://github.com/EclipseFdn/open-vsx.org/issues/676 durch ist
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/119"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Gitpod: bump latex workshop

- .gitpod.yml
vscode 1.60 unterstützt dieses feature nativ, man brauch keine extension mehr
ich würde mit mergen warten bis stable auf 1.60 gezogen ist. was meint ihr?
(falls jemand nicht latest eingestellt hat)
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/120"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> bracket pair colorizer aus gitpod entfernen

- Latex/literatur.bib
- Latex/vorlage.tex
Bei mehreren Quellen des selben Autors, wird der Name immer voll ausgeschrieben
Bei mehreren Quellen des selben Autors aus dem selben Jahr werden Buchstaben an der jahreszahl ergänzt
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/125"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Mehrere Autoren

- HINWEISE.md
Da inzwischen Minted bereits eine gewisse Standard-Konfiguration hat, können hier einige Optionen weg...
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/129"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Unnötige Minted-Argumente aus HINWEISE.md entfernt

- Latex/literatur.bib
- Latex/vorlage/vorlage.tex
laut [https://tex.stackexchange.com/a/621011/255865](https://tex.stackexchange.com/a/621011/255865)
fixes #138 
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/139"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix für Großschreibung von Autoren in Quellenverzeichnis

- Latex/vorlage/vorlage.tex
Fixes #114 
Außerdem werden dadurch Sonderzeichen durch die Schriftart statt durch LaTeX bestimmt. Das sorgt für eine veränderte Darsgtellung, bspw. bei Unterstrichen:
Vorher: 
Nachher:
Diff:
Erklärung: https://tex.stackexchange.com/questions/621131/fontenc-t1-changes-underscores
> Fontenc nutzen, um Umlaute korrekt zu codieren

- Latex/literatur.bib
- Latex/vorlage/Doku-Test.tex
- Latex/vorlage/vorlage.tex
- fixes #145
- entfernt außerdem ein überflüssiges Komma vor dem Abrufdatum einer Online-Quelle
- Beispielzitate in Doku-Test.tex
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/146"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> mehr als 3 Autoren korrigiert

- Latex/inhalt/Anhang.tex
- Latex/vorlage/vorlage.tex
- Latex/vorlage/vorlage_commands.tex
- Akronym gibt im Abkürzungsverzeichnis nur noch genutze Abkürzungen aus
- Refernzierung von Anhängen funktioniert
- im Anhang neu definiertes "bild"-Kommando angepasst
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/151"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Verschiedene Änderungen

- HINWEISE.md
- Latex/inhalt/Anhang.tex
- Latex/main.tex
- Latex/metadaten.sty
- Latex/vorlage/Doku-Test.tex
- Latex/vorlage/vorlage.tex
- automatisches Umschalten zwischen Erklärung / Titelseite für 1-4 Autoren anhand Metadaten.sty
- automatische Aktivieren des Abstracts / der Freigabeerklärung anhand Metadaten.sty
- automatisches Füllen der Autorenliste in den PDF-Metadaten, fixes #128 
- sinnlosen ersten Anhang entfernt und Doku-Test.tex entsprechend angepasst
fixes #50
<a href="https://gitpod.io/#https://github.com/DSczyrba/Vorlage-Latex/pull/154"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Automatische Versionen für 1-4 Autoren

- HINWEISE.md
- Latex/vorlage/Doku-Test.tex
- Latex/vorlage/vorlage_commands.tex
Die Formelumgebung ist sehr unhandlich. Hiermit wird ein eigenes Kommando für Formeln definiert
> Custom Command für Formeln

- Latex/vorlage/vorlage.tex
Nummerierung der Fußnoten wurde mit jedem Kapitel zurückgesetzt - behoben
> Fußnotennummerierung korrigiert

- Latex/vorlage/vorlage_subs/minted.tex
vorher:
nachher:
außerdem wird die Code-Float Position auf "h" gesetzt (statt "H"). In Situationen in denen das einen Unterschied macht, sollte h wahrscheinlich eh besser aussehen... H sollte nur eine manuelle Notfalloption sein
> Vspace vor Minted Umgebungen (und weniger militante Positionierung)

- HINWEISE.md
- Latex/inhalt/Anhang.tex
- Latex/light/vorlage_light.tex
- Latex/vorlage/Doku-Test.tex
- Latex/vorlage/vorlage_subs/custom_commands.tex
- Latex/vorlage/vorlage_subs/minted.tex
fixes #211
ähnlich wie von @ParkerSnable vorgeschlagen, habe ich die Platzierung auf `hptb` geändert.
Das ist immernoch weit weniger militant als `H`, priorisiert aber die gleiche Seite höher als `h`.
In der Doku-Test hat es dafür gesorgt, dass ich (mit etwas zusätzlichem Text) Verzeichnisbäume umstellen konnte, in meiner Bachelorthesis hat sich dadurch gegenüber `h` (dem aktuellen stand auf dev) absolut nichts geändert. Ich sehe also keine Nachteile.
> Geänderte Platzierung

- HINWEISE.md
- Latex/vorlage/Doku-Test.tex
- Latex/vorlage/vorlage_subs/custom_commands.tex
- literef und fullref finden nun selbst den Typ (Kapitel, Abbildung usw.)
- Abwärtskompatibilität ist gegeben (die alten Commands beziehen sich auf das neue)
- neues command "autoref" generiert `Typ #` (bspw. Unterabschnitt 2.2.3)
> Vereinfachung der Ref-Commands

- HINWEISE.md
- Latex/light/vorlage_light.tex
- Latex/vorlage/Doku-Test.tex
- Latex/vorlage/vorlage.tex
- Latex/vorlage/vorlage_subs/custom_commands.tex
- Latex/vorlage/vorlage_subs/minted.tex
- Spacing standardmäßig `htbp` (hier, top of page, bottom of page, page of floats)
- einheitliche Stelle, um Positionierung anzupassen (abgesehen von Code... das muss man aus Gründen in der TOC-Definition tun)
- einheitliches Spacing, unabhängig von der Positionierung (weil setspace nach float, tabularx usw. geladen)
- fixes #211 
einen Haken gibt es: das Spacing in allen Floats ist damit einheitlich 1. ich habe noch keinen Weg gefunden, überall z.B. 1.3 einzustellen
Für mich ist das kein Dealbreaker, weil einheitlich und leicht einstellbar.
> Neue Positionierung

- Latex/vorlage/vorlage.tex
TeXLive 2022 wirft in der aktuellen Konfiguration diese Warnung:
`main.tex:9: warning: [microtype] Unable to apply patch 'footnote'`
Ich war nicht in der Lage, die anders abzustellen.... Fußnoten sehen aber absolut normal aus
> Vorbereitung auf Container-Update

- .github/workflows/document-build.yml
test-run mit diff: https://github.com/ba-latex/Vorlage-Latex/actions/runs/3982069885
closes #225 
(nach dem merge dran denken, auch den `dev-actions-v3-test`-branch zu löschen - https://github.com/ba-latex/Vorlage-Latex/branches)
> deprecation warning in github actions beheben

- .vscode/settings.json
* ubuntu 22.10 base
* texlive 2022
* version pinning/langzeitstabilität
> container-update auf v1.7.1

- .github/workflows/document-build.yml
actions/{up,down}load-artifact v3 have long been deprecated and finally broke. none of the breaking changes in v4 should affect us, so this is a drop-in replacement
> ci: update github actions
